### ISSUE TITLE
Training stopped with memory leak(?) in the training step.

### ISSUE THREAD

**Issue by jgkimi** [acohan/long-summarization#3]
Hi. I'm simply trying to train a model on the sample file("small.bin") given here.

However, after a few seconds from running "run.sh", the training step seems stuck with memory explosion up to 100 % usage.
The step must be in the run_train_step() because it's showing "INFO:tensorflow:running training step..", but I cannot find the reason.

I use tensorflow v.1.5.0 and python 3.6 as recommended.

How could I solve this problem? Thank you.

**Comment by acohan** [comment]
What batch size are you using and what is your GPU? Have you tried decreasing batch size?

**Comment by jgkimi** [comment]
> What batch size are you using and what is your GPU? Have you tried decreasing batch size?

I ran the code with the given settings like batch size of 4.
I also modified to reduce the batch size to 2, but it doesn't work as well.

I use GTX 1080 on ubuntu 16.04, but GPU would not be the reason because the memory is not of GPU, but of CPU. GPU usage/total is about 600MB/8000MB, and its voltage is 0 showed by nvidia-smi (means it is not being used).

I think that some part of the model graphs is infinitely generated.

The debug mode doesn't also work with some exception error..

**Comment by acohan** [comment]
Could you set `coverage=False` in the `run.sh` script?

**Comment by jgkimi** [comment]
> Could you set `coverage=False` in the `run.sh` script and try again?

It works. :)

Are you going to provide a version of modifying that part?

Thank you for the fast response.

**Comment by acohan** [comment]
You should not start the program with coverage enabled. This is what I experienced in the original pointer-gen model as well. After some training steps, you can enable coverage.

Closing.
