### ISSUE TITLE
How to use the model on other dataset?

### ISSUE THREAD

**Issue by Tianwei-She** [acohan/long-summarization#4]
Hello,

I really enjoyed your paper and the code can run smoothly on the given tiny dataset. But when I tried to get it run on the downloaded Arxiv or PubMed data, the file format seems not fit. Also, I want to use this model on other dataset as our paper's baseline. 

I've tried the codes in scripts folder, which seems to be used for data preprocessing. But it takes xml file as input. 

If you can provide more detailed instructions on the data preprocessing, I'd greatly appreciate it.

**Comment by acohan** [comment]
I'll add the preprocessing steps to convert the data in the bin format. In the meanwhile, you can follow https://github.com/abisee/cnn-dailymail for preprocessing step. We only have an additional field called `sections`.

**Comment by soupstandstop** [comment]
Hi, 
I has already followed cnn-dailymail for preprocessing step,
pubmed_prep.py for pubmed's nxml
pubmed_write_bin.py for chunk file & .bin file
but, I still curious about read_tf_records_pubmed.py
what time we can use this ?

**Comment by Zierzzz** [comment]
Hello,
I want to use this model on my dataset， but the source text has no sections， can you give me some advice how to use your model?

**Comment by acohan** [comment]
Added a script that helps with preprocessing and converting the text files to Tensorflow bin files. https://github.com/acohan/long-summarization/blob/master/scripts/json_to_bin.py
